<?php
/**
 * Created by PhpStorm.
 * User: Ali
 * Date: 12/23/2016
 * Time: 1:28 PM
 */

return [
	'default' => 'azinweb',

	'gateway' => [
		'azinweb'       => [
			'website'    => 'http://azinweb.com',
			'webService' => 'http://sms.azin-sms.ir/API/send.asmx?WSDL',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'aradsms'       => [
			'website'    => 'http://arad-sms.ir',
			'webService' => 'http://panel.arad-sms.ir/post/send.asmx?wsdl',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'ariaideh'      => [
			'website'    => 'http://ariaideh.com',
			'webService' => 'http://sms.ariaideh.com/API/Send.asmx?WSDL',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'_0098sms'      => [
			'website'    => 'http://www.0098sms.com',
			'webService' => 'http://www.0098sms.com/',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'_500sms'       => [
			'website'    => 'http://500sms.ir',
			'webService' => 'http://500sms.ir/webservice/smsService.php?wsdl',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'adpdigital'    => [
			'website'    => 'http://adpdigital.com/services',
			'webService' => 'http://500sms.ir/webservice/smsService.php?wsdl',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'afe'           => [
			'website'    => 'http://afe.ir',
			'webService' => 'http://www.afe.ir/WebService/webservice.asmx?WSDL',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'afilnet'       => [
			'website'    => 'http://www.afilnet.com',
			'webService' => 'http://www.afilnet.com/ws/v2/index.php?wsdl',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'amansoft'      => [
			'website'    => 'http://sms.amansoft.ir',
			'webService' => 'http://sms.amansoft.ir/API/Send.asmx?WSDL',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'arkapayamak'   => [
			'website'    => 'http://www.arkapayamak.ir',
			'webService' => 'http://api.payamak-panel.com/post/send.asmx?WSDL',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'asanak'        => [
			'website'    => 'http://asanak.ir',
			'webService' => 'http://panel.asanak.ir/webservice/v1rest/sendsms',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'barmanpayamak' => [
			'website'    => 'http://asanak.ir',
			'webService' => 'http://www.barmanpayamak.ir',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'barzinsms'     => [
			'website'    => 'http://barzingostar.ir',
			'webService' => 'http://barzinsms.ir/post/send.asmx?wsdl',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'bearsms'       => [
			'website'    => 'http://www.bearsms.com',
			'webService' => 'http://app.bearsms.com/index.php?app=ws',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'bestit'        => [
			'website'    => 'http://panelsms.bestit.co',
			'webService' => 'http://panelsms.bestit.co/WsSms.asmx?wsdl',
			'username'   => '',
			'password'   => '',
			'from'       => '',
			'key'        => '',
		],
		'bulutfon'      => [
			'website'    => 'http://bulutfon.com',
			'webService' => 'https://api.bulutfon.com/messages',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'caffeweb'      => [
			'website'    => 'http://caffeweb.com',
			'webService' => 'http://sms.caffeweb.com/post/send.asmx?wsdl',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'chapargah'     => [
			'website'    => 'http://chapargah.ir',
			'webService' => 'http://panel.chapargah.ir/API/Send.asmx?WSDL',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'chaparpanel'   => [
			'website'    => 'http://chaparpanel.ir',
			'webService' => 'http://87.107.121.52/post/send.asmx?WSDL',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'difaan'        => [
			'website'    => 'http://csmsplus.mobilinkworld.com',
			'webService' => 'http://csmsplus.mobilinkworld.com/',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'dot4all'       => [
			'website'    => 'http://sms.dot4all.it',
			'webService' => 'http://sms.dot4all.it/sms/',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'esms24'        => [
			'website'    => 'http://esms24.ir',
			'webService' => 'http://esms24.ir/sendSmsViaURL.aspx',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'faraed'        => [
			'website'    => 'http://smspanel.faraed.com',
			'webService' => 'http://panelesms.net/SendMessage.ashx',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'farapayamak'   => [
			'website'    => 'http://www.farapayamak.com/',
			'webService' => 'http://api.payamak-panel.com/post/send.asmx?wsdl',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'farazpayam'   => [
			'website'    => 'http://farazpayam.com/',
			'webService' => 'http://farazpayam.com/API/Send.asmx?WSDL',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'fayasms'   => [
			'website'    => 'http://fayasms.ir/',
			'webService' => 'http://sms.fayasms.ir/post/send.asmx?wsdl',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'firstpayamak'   => [
			'website'    => 'http://firstpayamak.ir/',
			'webService' => 'http://ui.firstpayamak.ir/webservice/v2.asmx?WSDL',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'fortytwo'   => [
			'website'    => 'http://fortytwo.com/',
			'webService' => 'http://imghttp.fortytwotele.com/api/current',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'freepayamak'   => [
			'website'    => 'http://freepayamak.ir/',
			'webService' => 'http://sms.freepayamak.ir/post/send.asmx?wsdl',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'hostiran'   => [
			'website'    => 'http://sms.hostiran.net',
			'webService' => 'http://sms.hostiran.net/webservice/?WSDL',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
		'melipayamak'   => [
			'website'    => 'http://melipayamak.ir',
			'webService' => 'http://melipayamak.ir/post/send.asmx?wsdl',
			'username'   => '',
			'password'   => '',
			'from'       => '',
		],
        'itco'   => [
            'website'    => 'http://it-co.ir',
            'webService' => 'http://185.4.28.100/class/sms/webService4/server.php?wsdl',
            'username'   => '',
            'password'   => '',
            'from'       => '',
        ],
	],

];